CREATE TABLE  "SUBSCRIPTION" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"WORKSPACE_ID" NUMBER NOT NULL ENABLE, 
	"APPLICATION_ID" NUMBER NOT NULL ENABLE, 
	"PAGE_ID" NUMBER NOT NULL ENABLE, 
	"REPORT_TYPE" VARCHAR2(128) NOT NULL ENABLE, 
	"REPORT_ID" NUMBER NOT NULL ENABLE, 
	"STATIC_ID" VARCHAR2(256) NOT NULL ENABLE, 
	"APP_USER" VARCHAR2(256) NOT NULL ENABLE, 
	"SCHEDULED_JOB_NAME" VARCHAR2(256) NOT NULL ENABLE, 
	"EMAIL_FROM" VARCHAR2(256) NOT NULL ENABLE, 
	"EMAIL_ADDRESS" VARCHAR2(256) NOT NULL ENABLE, 
	"EMAIL_SUBJECT" VARCHAR2(1024) NOT NULL ENABLE, 
	"START_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"LANGUAGE" VARCHAR2(256) DEFAULT 'en-us', 
	"END_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"NOTIFY_INTERVAL" VARCHAR2(7) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(256) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(4000), 
	"QUERY_REPORT" CLOB NOT NULL ENABLE, 
	"ATTACH_FORMAT" VARCHAR2(64) DEFAULT 'HTML' --HTML, CSV, PDF
  , 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(256), 
	"UPDATED_ON" DATE DEFAULT SYSDATE, 
	"UPDATED_BY" VARCHAR2(256)
   )
/

CREATE UNIQUE INDEX  "SUBS_UK" ON  "SUBSCRIPTION" ("APP_USER", "EMAIL_ADDRESS", "REPORT_ID", "STATIC_ID")
/
